//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEstudiante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion
    {
        public int IdAsignacion { get; set; }
        public int EstudianteIdEstudiante { get; set; }
        public int CursoIdCurso { get; set; }
        public int notaFinal { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
