//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEstudiante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public Estudiante()
        {
            this.Asignaciones = new HashSet<Asignacion>();
        }
    
        public int IdEstudiante { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Asignacion> Asignaciones { get; set; }
    }
}
