//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosEstudiante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int IdTarea { get; set; }
        public string Tipo { get; set; }
        public int Nota { get; set; }
        public int AsignacionIdAsignacion { get; set; }
        public int CursoIdCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
